### ISSUE TITLE
#in_progress Criar componente para renderizar a Avatar do aluno

### ISSUE THREAD

**Issue by kevinDsousa** [dcTeam7/in_progress#10]
Criar um componente que deverá recebe a imagem de cada aluno do sistema.

Exemplo:

![Image](https://user-images.githubusercontent.com/55944691/229928797-a84970a0-9661-4e20-801e-3e4662983749.png)

```.js
function Image(props) {
  return (
    <img src={props.src} alt={props.alt} />
  );
}
```

**Comment by AbraaoAlves** [comment]
O nome do componente poderia ser `Avatar`
