### ISSUE TITLE
#in_progress ordenação por nome  (crescente / decrescente)

### ISSUE THREAD

**Issue by KevinDik** [dcTeam7/in_progress#12]
Componente informado deverá fazer uma ordenação por nome e ranquea-los tanto decrescente como crescente

**Comment by AbraaoAlves** [comment]
![Image](https://user-images.githubusercontent.com/608731/230384075-bc2b9e8f-a294-483b-ab5b-a68b7be23785.png)

Botão de ordenação por nome
