### ISSUE TITLE
#in_progress Alguns links de menu não estão funcionando

### ISSUE THREAD

**Issue by mikaelmonteirodev** [dcTeam7/in_progress#29]
Os links de menu _Descrição, Rodando local, Build, Deploy e Colaboradores_, estão com o link quebrado, pois a url contém duas hashs (#). O link da menu _Requisitos_ está ok.

Para corrigir basta retirar uma hash (#) do link.

**Comment by joellacerda** [comment]
Consertado.

**Comment by mikaelmonteirodev** [comment]
My friend @joellacerda ficou show! Só o _**Deploy**_ que ainda insistiu em não funcionar. 😄 
>
> ![image](https://user-images.githubusercontent.com/112489130/232818937-1d09373d-8d9b-4125-a32d-b7a96c6ec68d.png)
>
