### ISSUE TITLE
Descrever os pre-requisitos do README.md

### ISSUE THREAD

**Issue by KevinDik** [dcTeam7/in_progress#3]
## Pre-requisitos

Deverá informar qual será as ferramentas que precisam ser baixadas e como baixar o projeto.

### Exemplo:

- Informar as tecnologias que deverão ser baixadas com os links

NodeJS: ![NodeJS](https://img.shields.io/badge/node.js-6DA55F?style=for-the-badge&logo=node.js&logoColor=white)
VisualStudio: ![Visual Studio Code](https://img.shields.io/badge/Visual%20Studio%20Code-0078d7.svg?style=for-the-badge&logo=visual-studio-code&logoColor=white)

**Comment by mikaelmonteirodev** [comment]
@Paulo23ox assim como sugeriu o @joellacerda no comentário acima, aqui neste [Pull Request](https://github.com/dcTeam7/CalenDog/blob/5475d4b5d27fa939df76825ce4a8bb1b4e5cc9e8/README.md), enviado pelo @KevinDik, tem um ótimo exemplo de como resolver esta issue.

Aqui vai uma dica sugerida pelo @KevinDik de como realizar todo o procedimento de clonagem, branch, allteração no VSCode, Pull Request, etc. [Clique Aqui](https://www.alura.com.br/artigos/clonando-repositorio-git-github?gclid=CjwKCAjw0N6hBhAUEiwAXab-TdZQxLLdspbsffABqtypnuzP6FmjhM3RpYt7JUsARXyTJ4GKyuXRhhoCUREQAvD_BwE).

Vlw!
