### ISSUE TITLE
Rodando o projeto localmente documentação do README.md

### ISSUE THREAD

**Issue by KevinDik** [dcTeam7/in_progress#6]
### Exemplo:

- [ ] Como baixar o projeto
- [ ] Como inicializar o projeto

**Comment by joellacerda** [comment]
Dá uma olhada no #2 que tem uma ideia de como expor esses passos

**Comment by KevinDik** [comment]
Postaram esse link https://github.com/kentcdodds/advanced-react-hooks. Podemos usa-lo de isnpiração em algumas partes do README.md
